name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use Pre-installed Python
      run: python --version
    
    - name: Debug - List directory contents
      run: |
        echo "Listing root directory contents:"
        ls -la
        echo "Listing backend directory contents:"
        ls -la backend


    - name: Install system dependencies for Pillow
      run: sudo apt-get update && sudo apt-get install -y libjpeg-dev zlib1g-dev
    
    - name: Install Tesseract
      run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

    - name: Install dependencies
      run: |
        echo "Setting up virtual environment and installing dependencies..."
        python -m venv venv  
        source venv/bin/activate 
        pip install -r backend/requirements.txt  

    - name: Run tests
      run: |
        source venv/bin/activate  
        pytest tests/backend/ --maxfail=3 --tb=short > pytest-output.log
    
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest-output.log